# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x]
    name: Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: sequelize_test
          MYSQL_USER: sequelize_test
          MYSQL_PASSWORD: sequelize_test
          MYSQL_ROOT_PASSWORD: sequelize_test
        ports:
          - 3310:3306
        options: --health-cmd="mysqladmin -usequelize_test -psequelize_test status" --health-interval 10s --health-timeout 5s --health-retries 5 --tmpfs /var/lib/mysql:rw
    env:
      SEQ_PORT: 3310
      DIALECT: mysql
    steps:
      - run: if [ "$(dpkg -l | awk '/mysql-client/ {print }'|wc -l)" -eq 0 ]; then apt update && apt install mysql-client -y; fi
      - run: mysql --host 127.0.0.1 --port 3310 -uroot -psequelize_test -e "GRANT ALL ON *.* TO 'sequelize_test'@'%' with grant option; FLUSH PRIVILEGES;"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
      - run: npm test
